"""initial

Revision ID: 0001_initial
Revises: 
Create Date: 2025-10-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'usuarios',
        sa.Column('id_usuario', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('nombre', sa.String(length=200), nullable=False),
        sa.Column('edad', sa.Integer(), nullable=False),
        sa.Column('telefono', sa.String(length=20), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('password_salt', sa.String(length=64), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('id_usuario_creacion', sa.String(length=36), nullable=True),
        sa.Column('id_usuario_actualizacion', sa.String(length=36), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'mascotas',
        sa.Column('id_mascota', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('nombre', sa.String(length=50), nullable=False),
        sa.Column('tipo', sa.String(length=20), nullable=False),
        sa.Column('raza', sa.String(length=50), nullable=True),
        sa.Column('edad', sa.Integer(), nullable=True),
        sa.Column('peso', sa.Float(), nullable=True),
        sa.Column('propietario', sa.String(length=100), nullable=True),
        sa.Column('id_usuario_creacion', sa.String(length=36), nullable=True),
        sa.Column('id_usuario_actualizacion', sa.String(length=36), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'citas',
        sa.Column('id_cita', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('id_mascota', sa.String(length=36), nullable=False),
        sa.Column('fecha', sa.DateTime(), nullable=False),
        sa.Column('motivo', sa.String(length=200), nullable=True),
        sa.Column('veterinario', sa.String(length=100), nullable=True),
        sa.Column('estado', sa.String(length=20), nullable=True),
        sa.Column('id_usuario_creacion', sa.String(length=36), nullable=True),
        sa.Column('id_usuario_actualizacion', sa.String(length=36), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'vacunas',
        sa.Column('id_vacuna', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('id_mascota', sa.String(length=36), nullable=False),
        sa.Column('tipo_vacuna', sa.String(length=50), nullable=True),
        sa.Column('fecha_aplicacion', sa.Date(), nullable=True),
        sa.Column('veterinario', sa.String(length=100), nullable=True),
        sa.Column('lote_vacuna', sa.String(length=20), nullable=True),
        sa.Column('proxima_dosis', sa.Date(), nullable=True),
        sa.Column('id_usuario_creacion', sa.String(length=36), nullable=True),
        sa.Column('id_usuario_actualizacion', sa.String(length=36), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'facturas',
        sa.Column('id_factura', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('numero_factura', sa.String(length=50), nullable=False),
        sa.Column('id_mascota', sa.String(length=36), nullable=False),
        sa.Column('id_cita', sa.String(length=36), nullable=True),
        sa.Column('fecha_factura', sa.DateTime(), nullable=False),
        sa.Column('tipo_servicio', sa.String(length=50), nullable=True),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('veterinario', sa.String(length=100), nullable=True),
        sa.Column('valor_servicio', sa.Float(), nullable=True),
        sa.Column('iva', sa.Float(), nullable=True),
        sa.Column('descuento', sa.Float(), nullable=True),
        sa.Column('estado', sa.String(length=20), nullable=True),
        sa.Column('total', sa.Float(), nullable=True),
        sa.Column('id_usuario_creacion', sa.String(length=36), nullable=True),
        sa.Column('id_usuario_actualizacion', sa.String(length=36), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'recetas',
        sa.Column('id_receta', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('id_cita', sa.String(length=36), nullable=False),
        sa.Column('fecha_emision', sa.DateTime(), nullable=False),
        sa.Column('veterinario', sa.String(length=100), nullable=True),
        sa.Column('indicaciones', sa.Text(), nullable=True),
        sa.Column('id_usuario_creacion', sa.String(length=36), nullable=True),
        sa.Column('id_usuario_actualizacion', sa.String(length=36), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'receta_lineas',
        sa.Column('id_receta_linea', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('id_receta', sa.String(length=36), nullable=False),
        sa.Column('medicamento', sa.String(length=200), nullable=False),
        sa.Column('dosis', sa.String(length=100), nullable=True),
        sa.Column('frecuencia', sa.String(length=100), nullable=True),
        sa.Column('duracion', sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receta_lineas')
    op.drop_table('recetas')
    op.drop_table('facturas')
    op.drop_table('vacunas')
    op.drop_table('citas')
    op.drop_table('mascotas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
def upgrade():
    # Usuarios
    op.add_column('usuarios', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('usuarios', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('deleted_by', sa.String(36), nullable=True))
    
    # Mascotas
    op.add_column('mascotas', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('mascotas', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('mascotas', sa.Column('deleted_by', sa.String(36), nullable=True))
    
    # Citas
    op.add_column('citas', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('citas', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('citas', sa.Column('deleted_by', sa.String(36), nullable=True))
    
    # Vacunas
    op.add_column('vacunas', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('vacunas', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('vacunas', sa.Column('deleted_by', sa.String(36), nullable=True))
    
    # Facturas
    op.add_column('facturas', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('facturas', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('facturas', sa.Column('deleted_by', sa.String(36), nullable=True))
    
    # Recetas
    op.add_column('recetas', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('recetas', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('recetas', sa.Column('deleted_by', sa.String(36), nullable=True))


def downgrade():
    # Usuarios
    op.drop_column('usuarios', 'deleted_by')
    op.drop_column('usuarios', 'deleted_at')
    op.drop_column('usuarios', 'is_deleted')
    
    # Mascotas
    op.drop_column('mascotas', 'deleted_by')
    op.drop_column('mascotas', 'deleted_at')
    op.drop_column('mascotas', 'is_deleted')
    
    # Citas
    op.drop_column('citas', 'deleted_by')
    op.drop_column('citas', 'deleted_at')
    op.drop_column('citas', 'is_deleted')
    
    # Vacunas
    op.drop_column('vacunas', 'deleted_by')
    op.drop_column('vacunas', 'deleted_at')
    op.drop_column('vacunas', 'is_deleted')
    
    # Facturas
    op.drop_column('facturas', 'deleted_by')
    op.drop_column('facturas', 'deleted_at')
    op.drop_column('facturas', 'is_deleted')
    
    # Recetas
    op.drop_column('recetas', 'deleted_by')
    op.drop_column('recetas', 'deleted_at')
    op.drop_column('recetas', 'is_deleted')
